plugins { id 'com.android.application' }

android {
    namespace 'zw.co.doublegeetech.schoolerp'
    compileSdk 35

    defaultConfig {
        applicationId 'zw.co.doublegeetech.schoolerp'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {}
